Diizzayy/nuxt-graphql-client

.gitignore, package.json, src/generate.ts, yarn.lock
Applies fix suggested by @FWORDIE  to close #26 
This PR applies a default naming convention to enums to prevent encountering duplicate identifiers
=> fix: apply default naming convention to address duplicate identifiers

playground/package.json, src/generate.ts, src/module.ts
Closes #15
Current implementation of `@graphql-codegen/cli` fails to resolve plugins when ran on windows.
This PR generates the necessary graphql-codegen config file (`.graphqlrc`) in the project root when needed and leverages `loadCodegenConfig` to circumvent this issue.
=> fix: use codegen config for windows

src/context.ts, src/generate.ts, src/module.ts
Closes #36
As suggested by @DenisNikonov. This PR allows an optional GraphQL Schema file to be provided to clients, doing so forgoes the default behavior of querying the host for code generation.
- Clients now take an optional `schema` parameter which should point to the relative path of the GraphQL Schema file.
```diff
export default defineNuxtConfig({
modules: ['nuxt-graphql-client'],
runtimeConfig: {
public: {
'graphql-client': {
clients: {
default: {
host: 'https://api.spacex.land/graphql'
},
pokemon: {
+          schema: './schemas/pokemon.graphql',
host: 'https://graphqlpokemon.favware.tech'
}
}
}
}
}
})
```
=> feat: allow schema to be provided for code generation

src/generate.ts, src/module.ts, src/runtime/composables.ts, src/runtime/utils.ts
Closes #48
This PR allows authenticated requests to be made without an `auth-scheme` (such as Bearer).
API's as Shopify Admin & Storefront require the authentication header to be made simple as `X-Shopify-Storefront-Access-Token: <YOUR_TOKEN>`.
=> fix: allow authentication without `auth-scheme`

docs/content/en/advanced/authentication.md, docs/content/en/getting-started/configuration.md, src/module.ts
Closes #54 
This PR introduces a `retainToken` flag to the client configuration.
Default behavior of this module only applies config-level tokens ( set by `runtimeConfig` or `environment variables` ) to the server side for code generation and SSR requests, the purpose of this being to prevent leaking private tokens to the browser.
The `retainToken` flag circumvents this behavior and retains said tokens to the client-side.
_**This flag should be used with caution as it indeed poses the risk of exposing private tokens client-side!**_
```diff
runtimeConfig: {
public: {
'graphql-client': {
clients: {
default: 'https://api.spacex.land/graphql',
github: {
host: 'https://api.github.com/graphql',
token: '<your-github-token>', // overwritten by process.env.GQL_GITHUB_TOKEN
+ …
```
=> feat: allow config-level tokens to be retained on client-side

package.json, yarn.lock
Affected #68
This PR uses [unjs/node-fetch-native](https://github.com/unjs/node-fetch-native) to prevent the case where multiple versions of `node-fetch` exist within your dependencies.
=> fix: `node-fetch` compatibility

src/module.ts, src/runtime/composables.ts
Closes #74
This PR introduces an optional `clientHost` option, when set client side requests will be directed to it's provided value.
=> feat: support optional `clientHost`

src/runtime/composables/index.ts
This PR allows the `useGqlToken` composable to strip the pertinent auth header by passing nullish values.
=> fix: completely strip auth header

module/src/runtime/composables/index.ts
`useGql.handle` in `nuxt-graphql-client/dist/runtime/composables/index.d.ts` is currently typed as `handle: (client?: GqlClients) => any;`, breaking return types for `GqlFunc` defined as `type GqlFunc = ReturnType<ReturnType<typeof import('#imports')['useGql']>['handle']>` (generated `Gql*` functions always returns `any`).
This update adds an explicit return type to `handle` as `useGql` was typed before [being refactored here](https://github.com/Diizzayy/nuxt-graphql-client/pull/132/files#diff-94c56e8a509ace6761f1407afc52e10a703e013020b716d6957057286d8116b6L269)
=> fix: Gql functions return type 

docs/content/1.getting-started/1.quick-start.md, docs/content/1.getting-started/2.composables.md, module/package.json, module/src/context.ts, module/src/module.ts, module/src/runtime/composables/index.ts, package.json, playground/app.vue, test/fixtures/basic/app.vue, yarn.lock
This PR introduces a new composable `useAsyncGql` which leverages [`useAsyncData`](https://v3.nuxtjs.org/api/composables/use-async-data) under the hood.
Before:
```ts
const { data } = await useAsyncData('<data-key>', () => GqlLaunches({ limit: 5 }))
```
After: 
```ts
const { data } = await useAsyncGql('launches', { limit: 5 });
```
```ts
const { data } = await useAsyncGql({
operation: 'launches',
variables: { limit: 5 }
});
```
=> feat: `useAsyncGql` data fetching

module/src/module.ts
This module currently omits any `.gql` or `.graphql` files in the `/schemas` directory from evaluation, This PR minimally extends upon that to also exclude files which contain the word `schema` in the file name as a preventative measure.
Closes #156
=> fix: filter documents named `schema`

src/module.ts
In https://github.com/nuxt/framework/pull/7116 we made a breaking change allowing modules to use RC constraints. This PR fixes this.
=> fix: update nuxt compatibility

package-lock.json, src/runtime/composables/index.ts
Hiya!
I created a small PR to allow `null` to be passed as the token from a TS perspective.
Also added the `GqlToken` type for this.
Currently `null` is not allowed to be passed, because the type is set as `string` only, which throws TS errors.
=> fix: type `useGqlToken`

src/module.ts
This PR fixes a bug that causes `proxyCookies` ( should be enabled by default ) to be disabled when using a single client declared via `GQL_HOST`
=> fix: properly apply cookie proxy

src/module.ts
This PR fixes a regression introduced in #153 which prevents operations prefixed with a client name for multi-client mode to retain the client name, This in turn cause `useAsyncGql` to fail when a prefixed operation is used.
Closes #193
=> fix: prepare operations before template

docs/content/1.getting-started/3.configuration.md, docs/package.json, src/generate.ts, src/runtime/plugin.ts, src/types.d.ts
This PR enables declaring server-only headers at the client configuration level as seen below. Entries within the `serverOnly` property will only be applied server side, whereas other properties within `headers` will be applied on both client and server side.
```ts
export default defineNuxtConfig({
runtimeConfig: {
public: {
'graphql-client': {
clients: {
default: {
host: '<graphql_api>',
headers: {
'X-CUSTOM-HEADER': '',
serverOnly: {
'X-SERVER-ONLY': ''
}
}
}
}
}
}
}
})
```
=> feat: server only headers

docs/content/1.getting-started/3.configuration.md, src/module.ts, src/runtime/plugin.ts, src/types.d.ts
This PR introduces a new `preferGETQueries` flag which when enabled, sends all query requests using the HTTP `GET` method.
Closes #219
=> feat: allow sending queries with GET method

docs/content/1.getting-started/3.configuration.md, package.json, pnpm-lock.yaml, src/generate.ts, src/module.ts, src/types.d.ts, test/fixtures/multi-client/nuxt.config.ts, test/fixtures/multi-client/package.json, test/fixtures/multi-client/pages/index.vue, test/fixtures/multi-client/pages/rmorty/first-ep.vue, test/fixtures/multi-client/pages/rmorty/index.vue, test/fixtures/multi-client/pages/spacex/index.vue, test/fixtures/multi-client/pages/spacex/mission.vue, test/fixtures/multi-client/queries/dual_clients.gql, test/fixtures/multi-client/queries/rmorty/ep.gql, test/fixtures/multi-client/queries/spacex/mission.gql, test/multi-client.test.ts
This PR aims to address common conflicts when using multiple GraphQL APIs (multiple client mode).
When using multiple large GraphQL APIs, the likelihood of their underlying types and operations overlapping vastly increases, hence the default merging strategy used by `graphql-codegen` is at times unable to merge the schemas in aims of understanding the configured clients.
=> feat: schema stitching

src/generate.ts, src/module.ts, src/types.d.ts
This PR allows specifying headers that should only be applied to the graphql code generator, which don't necessarily need to be applied server wide.
=> feat: allow declaring codegen headers

src/runtime/composables/index.ts
This PR adds missing `useCookie` import. Without it, usage of `useGqlToken` fails:
`Uncaught (in promise) ReferenceError: useCookie is not defined`
=> fix: add missing useCookie import

src/runtime/composables/index.ts
In my previous PR #263 I forgot to add `unref(variables)` in `useGql`: 
```js
return useAsyncData(key, () => useGql()(operation, unref(variables)), options)
```
But when I add it I get the error below:
```
Uncaught (in promise) TypeError: $setup.data is null
``` 
This fixes the issue by wrapping  the variables in a `reactive` object. Apologies for not testing properly before submitting the previous PR.
=> Fix reactive variables in useAsyncGql

docs/content/1.getting-started/4.configuration.md, src/generate.ts, src/module.ts, src/types.d.ts
Resolve: Enhanced codegen config add maybeValue option #405
Permit to use code generation with key?: T instead key: T | null because when we define gql query without some property we expect that the undefined property doesn't exists. That's different from exists with null value
=> feat: add maybeValue option on codegen options (#405)

src/runtime/composables/index.ts, src/runtime/plugin.ts
This is a very early PR to make this module compatible with [changes we expect to release in Nuxt v5](https://github.com/nuxt/nuxt/issues/25323).
In [Nuxt v3.7.0](https://github.com/nuxt/nuxt/releases/tag/v3.7.0) we added support for `import.meta.*` (see [original PR](https://github.com/nuxt/nuxt/pull/22428)) and we've been gradually updating docs and moving across from the old `process.*` patterned variables.
As I'm sure you're aware, these variables are replaced at build-time and enable tree-shaking in bundled code.
This change affects _runtime_ code (that is, that is processed by the Nuxt bundler, like vite or webpack) rather than code running in Node. So it really doesn't matter what the string is, but it makes more sense in an ESM-world to use `import.meta` rather than `process`.
(It …
=> fix: opt in to `import.meta.*` properties

docs/content/1.getting-started/1.quick-start.md, docs/content/1.index.md
This updates the documentation to use the [`nuxi module add` command](https://github.com/nuxt/cli/pull/197) which should simplify docs a bit and also improve user experience as there's no need to add to `nuxt.config` manually.
It's documented [here](https://nuxt.com/docs/api/commands/module#nuxi-module-add).
I may have missed a few spots in the documentation as I'm doing this across the modules ecosystem assisted by the power of regular expressions ✨, so I'd appreciate a review 🙏
=> docs: use new `nuxi module add` command in installation

src/module.ts
issue: https://github.com/Diizzayy/nuxt-graphql-client/issues/468
export the type GqlError used in useGqlError
That's all!
The types.d.ts of the dist will look like this
=> export type GqlError

docs/content/1.getting-started/4.configuration.md, src/runtime/nitro.ts, src/runtime/plugin.ts, src/types.d.ts
Adds a `fetchOptions` key to GraphQL client config to allow further customization when defining a client in Nuxt config.
See https://github.com/jasonkuhrt/graphql-request#configuration
=> Allow additional `graphql-request` fetch options configuration.

docs/content/1.getting-started/4.configuration.md
Fixes broken link - reference to nuxt runtime config docs
=> docs: fix broken link to nuxt runtime config

docs/content/1.getting-started/4.configuration.md, src/generate.ts, src/module.ts, src/types.d.ts
I have added support for scalar overwrites, a feature that was previously missing. This change also addresses and resolves two related tickets.
- https://github.com/Diizzayy/nuxt-graphql-client/issues/355
- https://github.com/Diizzayy/nuxt-graphql-client/issues/451
=> feat: expose the codegen scalars

src/utils.ts
Fixed the GraphQL document file to work with the default client or when no client is specified.
**Issue**
```sh
ERROR  Invalid Codegen Configuration!
Please make sure that your codegen config file contains the "generates" field, with a specification for the plugins you need.
It should looks like that:
schema:
- my-schema.graphql
generates:
my-file.ts:
- plugin1
- plugin2
- plugin3
```
=> Fixed `clientInExt` regex for `document without client

docs/content/1.getting-started/4.configuration.md, src/generate.ts, src/module.ts, src/types.d.ts
This PR adds support for two additional [graphql-codegen](https://the-guild.dev/graphql/codegen) options in `nuxt-graphql-client`:
- `enumsAsTypes`: Outputs GraphQL enums as union string literal types (`'A' | 'B'`) instead of TypeScript `enum`.
- `enumsAsConst`: Appends `as const` to enum objects to allow usage as readonly values in generated artifacts.
```ts
export type SortOrder = 'asc' | 'desc'; // ✅ instead of `enum SortOrder { ... }`
=> feat: expose enumsAsTypes and enumsAsConst options
